name: Python Package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies and disable IPv6
        run: |
          sudo snap install dotnet-sdk --classic
          sudo snap alias dotnet-sdk.dotnet dotnet
          sudo add-apt-repository -y ppa:ubuntugis/ppa
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev
          sudo apt-get install -y --no-install-recommends libffi-dev
          sudo apt-get install -y --no-install-recommends lzma liblzma-dev
          sudo apt-get install -y --no-install-recommends libgeos-dev libgeos++-dev
          sudo apt-get install -y --no-install-recommends libproj-dev proj-data proj-bin
          sudo apt-get install -y --no-install-recommends libsnappy-dev
          sudo apt-get install -y --no-install-recommends python3-h5py
          sudo apt-get install -y --no-install-recommends gdal-bin libgdal-dev python3-gdal
          python -m pip install --upgrade pip poetry

      - name: Run tox
        env:
          DOTNET_ROOT: /snap/dotnet-sdk/current
        run: |
          poetry config repositories.repogetfeed https://pkgs.dev.azure.com/org/_packaging/pypigetfeed/pypi/simple/
          poetry config http-basic.pypigetfeed SVC_github-ci ${{ secrets.BOT_pypigetfeed_FEED_PAT }}
          poetry export -f requirements.txt --dev --with-credentials --without-hashes -o requirements.txt
          poetry run pip install -r requirements.txt
          echo "" > requirements.txt  # prevents liccheck falling over
          make test-all
